# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Tag(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, active: bool=True):  # noqa: E501
        """Tag - a model defined in Swagger

        :param name: The name of this Tag.  # noqa: E501
        :type name: str
        :param active: The active of this Tag.  # noqa: E501
        :type active: bool
        """
        self.swagger_types = {
            'name': str,
            'active': bool
        }

        self.attribute_map = {
            'name': 'name',
            'active': 'active'
        }
        self._name = name
        self._active = active

    @classmethod
    def from_dict(cls, dikt) -> 'Tag':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tag of this Tag.  # noqa: E501
        :rtype: Tag
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Tag.


        :return: The name of this Tag.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Tag.


        :param name: The name of this Tag.
        :type name: str
        """

        self._name = name

    @property
    def active(self) -> bool:
        """Gets the active of this Tag.


        :return: The active of this Tag.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this Tag.


        :param active: The active of this Tag.
        :type active: bool
        """

        self._active = active
